server:
  port: 8085

spring:
  application:
    name: user-pet-service
  main:
    banner-mode: off
  jackson:
    # ?? ?????????? ???? ? null ?????????? ???????
    default-property-inclusion: non_null
    deserialization:
      #?????? ??? ?????? ?????
      fail-on-unknown-properties: true
      #??????, ???? JSON ??????
      fail-on-ignored-properties: true
      #???????????? ?????? ?????? "" ??? null
      accept-empty-string-as-null-object: true
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-doc:
    path: /api-doc
  swagger-ui:
    path: /swagger-ui.html
    enable: true

logging:
  level:
    root: info
  file:
    name: logs/users-pets.log
  pattern:
    file: "%d{yyy-MM-dd HH:mm:ss} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

